"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import auth.auth_pb2
import grpc

class AuthStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Authenticate: grpc.UnaryUnaryMultiCallable[
        auth.auth_pb2.AuthenticateRequest,
        auth.auth_pb2.AuthenticateResponse]
    """Web apps should never call this directly."""

    Refresh: grpc.UnaryUnaryMultiCallable[
        auth.auth_pb2.RefreshRequest,
        auth.auth_pb2.RefreshResponse]
    """Refresh can be called via web too."""


class AuthServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Authenticate(self,
        request: auth.auth_pb2.AuthenticateRequest,
        context: grpc.ServicerContext,
    ) -> auth.auth_pb2.AuthenticateResponse:
        """Web apps should never call this directly."""
        pass

    @abc.abstractmethod
    def Refresh(self,
        request: auth.auth_pb2.RefreshRequest,
        context: grpc.ServicerContext,
    ) -> auth.auth_pb2.RefreshResponse:
        """Refresh can be called via web too."""
        pass


def add_AuthServicer_to_server(servicer: AuthServicer, server: grpc.Server) -> None: ...
