"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import shared.feature_toggle_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor


class FetchRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PLATFORM_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    platform: shared.feature_toggle_pb2.Platform.Type.ValueType
    version: builtins.int

    def __init__(
        self,
        *,
        platform: shared.feature_toggle_pb2.Platform.Type.ValueType = ...,
        version: builtins.int = ...,
    ) -> None:
        ...

    def ClearField(
        self, field_name: typing_extensions.Literal["platform", b"platform",
                                                    "version", b"version"]
    ) -> None:
        ...


global___FetchRequest = FetchRequest


class FetchResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FEATURE_TOGGLES_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int

    @property
    def feature_toggles(
        self
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
            shared.feature_toggle_pb2.FeatureToggle]:
        ...

    version: builtins.int

    def __init__(
        self,
        *,
        feature_toggles: typing.Optional[typing.Iterable[
            shared.feature_toggle_pb2.FeatureToggle]] = ...,
        version: builtins.int = ...,
    ) -> None:
        ...

    def ClearField(
        self, field_name: typing_extensions.Literal["feature_toggles",
                                                    b"feature_toggles",
                                                    "version", b"version"]
    ) -> None:
        ...


global___FetchResponse = FetchResponse


class ListenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PLATFORM_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    platform: shared.feature_toggle_pb2.Platform.Type.ValueType
    version: builtins.int

    def __init__(
        self,
        *,
        platform: shared.feature_toggle_pb2.Platform.Type.ValueType = ...,
        version: builtins.int = ...,
    ) -> None:
        ...

    def ClearField(
        self, field_name: typing_extensions.Literal["platform", b"platform",
                                                    "version", b"version"]
    ) -> None:
        ...


global___ListenRequest = ListenRequest


class ListenPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FEATURE_TOGGLES_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int

    @property
    def feature_toggles(
        self
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
            shared.feature_toggle_pb2.FeatureToggle]:
        ...

    version: builtins.int

    def __init__(
        self,
        *,
        feature_toggles: typing.Optional[typing.Iterable[
            shared.feature_toggle_pb2.FeatureToggle]] = ...,
        version: builtins.int = ...,
    ) -> None:
        ...

    def ClearField(
        self, field_name: typing_extensions.Literal["feature_toggles",
                                                    b"feature_toggles",
                                                    "version", b"version"]
    ) -> None:
        ...


global___ListenPayload = ListenPayload
