"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class User(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class VerifiableAddress(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        ADDRESS_FIELD_NUMBER: builtins.int
        VERIFIED_FIELD_NUMBER: builtins.int
        address: typing.Text
        verified: builtins.bool
        def __init__(self,
            *,
            address: typing.Text = ...,
            verified: builtins.bool = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["address",b"address","verified",b"verified"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    ORY_ID_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    ADDRESSES_FIELD_NUMBER: builtins.int
    RECOVERY_ADDRESSES_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    PROFILE_FIELD_NUMBER: builtins.int
    id: typing.Text
    ory_id: typing.Text
    first_name: typing.Text
    last_name: typing.Text
    @property
    def addresses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___User.VerifiableAddress]: ...
    @property
    def recovery_addresses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___User.VerifiableAddress]: ...
    domain: typing.Text
    profile: typing.Text
    def __init__(self,
        *,
        id: typing.Text = ...,
        ory_id: typing.Text = ...,
        first_name: typing.Text = ...,
        last_name: typing.Text = ...,
        addresses: typing.Optional[typing.Iterable[global___User.VerifiableAddress]] = ...,
        recovery_addresses: typing.Optional[typing.Iterable[global___User.VerifiableAddress]] = ...,
        domain: typing.Text = ...,
        profile: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["addresses",b"addresses","domain",b"domain","first_name",b"first_name","id",b"id","last_name",b"last_name","ory_id",b"ory_id","profile",b"profile","recovery_addresses",b"recovery_addresses"]) -> None: ...
global___User = User
